#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 12 06:55:59 2020

@author: prasanthchakka
"""

#%%

text = "This is this is what what is a that that this that"

def create_freq_dict(words):
    my_list = words.split()
    frequencies = {}
    
    for word in my_list:
        if word in frequencies:
            frequencies[word] += 1
        else:
            frequencies[word] = 1
            
    return frequencies

my_dict = create_freq_dict(text)
        
#%%

def print_frequencies(frequencies_dictionary):
    longest = 0
    for word in frequencies_dictionary:
        if len(word) > longest:
            longest = len(word)
            
    for word in frequencies_dictionary:
        num_spaces = longest - len(word)
        print(word + (" "*num_spaces) +"|" + ("*"*frequencies_dictionary[word]))
        
        
print_frequencies(my_dict)
